{{- if eq .Values.components.code.enabled true }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: code
  name: code
spec:
  type: ClusterIP
  ports:
  - name: code
    port: 3000
    targetPort: 8080
  selector:
    app: code
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: code
  name: hugo
spec:
  type: ClusterIP
  ports:
  - name: hugo
    port: 1313
  selector:
    app: code
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: code
  name: code
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: code
  template:
    metadata:
      labels:
        app: code
    spec:
      initContainers:
      - image: {{ .Values.docker.registry }}/cloud-native-workstation-code-server:{{ .Values.docker.tag }}
        imagePullPolicy: Always
        name: permissions
        securityContext:
          runAsUser: 0
        command: ["/bin/bash", "-c"]
        args:
        - "chown -R coder: /home/coder"
        volumeMounts:
        - name: coder
          mountPath: /home/coder
          subPath: home/coder
      containers:
      - image: {{ .Values.docker.registry }}/cloud-native-workstation-code-server:{{ .Values.docker.tag }}
        imagePullPolicy: Always
        name: code
        ports:
        - name: ide
          containerPort: 3000
        - name: hugo
          containerPort: 1313
        env:
        - name: PATH
          value: "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin:/home/coder/bin:/home/coder/.local/bin"
        - name: DOCKER_HOST
          value: tcp://localhost:2375
        - name: PASSWORD
          value: "{{ .Values.authentication.password }}"
        securityContext:
          privileged: true
        resources: {{- toYaml .Values.components.code.resources | nindent 10 }}
        volumeMounts:
        - name: coder
          mountPath: /home/coder
          subPath: home/coder
      - name: dind-daemon
        image: {{ .Values.components.code.dind.image }}:{{ .Values.components.code.dind.tag }}
        env:
        - name: DOCKER_TLS_CERTDIR
          value: ""
        securityContext:
          privileged: true
        resources: {{- toYaml .Values.components.code.dind.resources | nindent 10 }}
        volumeMounts:
          - name: code-dind-pv
            mountPath: /var/lib/docker
            subPath: var/lib/docker
      volumes:
      - name: coder
        persistentVolumeClaim:
          claimName: coder-pvc
      - name: code-dind-pv
        persistentVolumeClaim:
          claimName: code-dind-pvc
      restartPolicy: Always
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: coder-pvc
  labels:
    app: code
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: code-dind-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
{{- end }}