---
apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-init
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana-init
spec:
  template:
    metadata:
      labels:
        app: grafana-init
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      containers:
      - name: seed
        image: {{ .Values.docker.registry }}/cloud-native-workstation-initializers:{{ .Values.docker.tag }}
        imagePullPolicy: Always
        command: ["/bin/bash", "-c"]
        args:
        - |
          /opt/seed.sh || exit $?
        env:
        - name: USERNAME
          value: {{ .Values.authentication.username }}
        - name: PASSWORD
          value: {{ .Values.authentication.password }}
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
        resources: {{- toYaml .Values.components.initializers.resources | nindent 10 }}
        volumeMounts:
        - name: grafana-seed-sh
          mountPath: /opt/seed.sh
          subPath: seed.sh
      volumes:
      - name: grafana-seed-sh
        configMap:
          name: grafana-seed-sh
          defaultMode: 0555
      restartPolicy: Never
  backoffLimit: 32
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-seed-sh
  namespace: {{ .Values.namespace }}
data:
  seed.sh: |
    #!/bin/bash
    # https://community.grafana.com/t/is-there-an-equivalent-http-api-to-import-a-dashboard-from-grafana-com/9581/2
    grafana_host="http://grafana:3030"
    grafana_cred="$USERNAME:$PASSWORD"
    grafana_datasource="Prometheus"

    paths=(dashboards/prometheus_stats.json dashboards/prometheus_2_stats.json dashboards/grafana_stats.json )
    for path in "${paths[@]}"; do
      echo "Processing $path: "
      curl -s -k -u "$grafana_cred" -XPOST -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        -d "{
          \"overwrite\":true, \
          \"pluginId\":\"prometheus\", \
          \"path\":\"$path\",
          \"inputs\":[{ \
            \"name\":\"*\", \
            \"type\":\"datasource\", \
            \"pluginId\":\"prometheus\", \
            \"value\":\"$grafana_datasource\" \
          }] \
          }" \
        $grafana_host/api/dashboards/import || exit $?
      echo ""
    done

    ds=(13332 )
    for d in "${ds[@]}"; do
      echo "Processing $d: "
      j=$(curl -s -k -u "$grafana_cred" $grafana_host/api/gnet/dashboards/$d | jq .json)
      curl -s -k -u "$grafana_cred" -XPOST -H "Accept: application/json" \
        -H "Content-Type: application/json" \
        -d "{ \
          \"dashboard\":$j, \
          \"overwrite\":true, \
          \"inputs\":[ \
            { \
              \"name\":\"DS_PROMETHEUS\", \
              \"type\":\"datasource\", \
              \"pluginId\":\"prometheus\", \
              \"value\":\"$grafana_datasource\" \
            }, \
            { \
              \"name\":\"VAR_DATASOURCE\", \
              \"type\":\"constant\", \
              \"value\":\"$grafana_datasource\" \
            } \
          ] \
        }" \
        $grafana_host/api/dashboards/import; echo ""
    done
{{- if eq .Values.policies.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: grafana-init
  namespace: cloud-native-workstation
spec:
  podSelector:
    matchLabels:
      app: grafana-init
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - {}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: grafana
{{- end }}