---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak-postgres
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      containers:
      - image: postgres:9.6
        name: postgres
        env:
        - name: POSTGRES_USER
          value: {{ .Values.authentication.username }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.authentication.password }}
        - name: POSTGRES_DB
          value: keycloak
        ports:
        - containerPort: 5432
          name: postgresql
        resources: {{- toYaml .Values.components.keycloak.postgres.resources | nindent 10 }}
        volumeMounts:
        - name: keycloak-postgres
          mountPath: /var/lib/postgresql/data
          subPath: postgres
      volumes:
      - name: keycloak-postgres
        persistentVolumeClaim:
          claimName: keycloak-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak-postgres
spec:
  ports:
  - port: 5432
  selector:
    app: keycloak-postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-postgres-pvc
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak-postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 32Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      containers:
      - image: jboss/keycloak:7.0.0
        name: keycloak
        env:
        - name: DB_VENDOR
          value: "postgres"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: {{ .Values.authentication.username }}
        - name: DB_PASSWORD
          value: {{ .Values.authentication.password }}
        - name: DB_DATABASE
          value: "keycloak"
        - name: DB_ADDR
          value: "keycloak-postgres"
        - name: KEYCLOAK_USER
          value: {{ .Values.authentication.username }}
        - name: KEYCLOAK_PASSWORD
          value: {{ .Values.authentication.password }}
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"
        - name: KEYCLOAK_LOGLEVEL
          value: "DEBUG"
        securityContext:
          runAsNonRoot: true
        resources: {{- toYaml .Values.components.keycloak.resources | nindent 10 }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak
spec:
  type: ClusterIP
  ports:
  - name: keycloak
    protocol: TCP
    port: 8080
  selector:
    app: keycloak
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak-gatekeeper
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak-gatekeeper
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak-gatekeeper
  template:
    metadata:
      labels:
        app: keycloak-gatekeeper
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      containers:
      {{- $root := . }}
      {{- range .Values.access }}
      - image: keycloak/keycloak-gatekeeper:7.0.0
        name: gatekeeper-{{ .name }}
        ports:
        - containerPort: {{ .port }}
          name: listen
        securityContext:
          readOnlyRootFilesystem: true
        resources: {{- toYaml $root.Values.components.keycloak.gatekeepers.resources | nindent 10 }}
        args:
        - --listen=:{{ .port }}
        - --preserve-host=true
        - --discovery-url=https://{{ $root.Values.domain }}:8080/auth/realms/master
        - --oauth-uri=/devtools-oath
        - --upstream-url=http://{{ .name }}:{{ .port }}
        - --verbose=true
        - --resources=uri=/*|methods=GET
        - --skip-openid-provider-tls-verify=true
        - --encryption-key={{ $root.Values.keycloak.encryptionKey }}
        - --enable-refresh-tokens=true
        - --enable-encrypted-token=false
        - --cookie-refresh-name=kc-refresh-token
        - --enable-authorization-header=false
        - --client-id={{ .name }}
        - --client-secret={{ $root.Values.keycloak.clientSecret }}
        - --client-auth-method=secret-body
        - --server-read-timeout=50s
        - --server-write-timeout=50s
      {{- end }}
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-gatekeeper
  namespace: {{ .Values.namespace }}
  labels:
    app: keycloak-gatekeeper
spec:
  type: ClusterIP
  ports:
  {{- range .Values.access }}
  - name: {{ .name }}
    port: {{ .port }}
  {{- end }}
  selector:
    app: keycloak-gatekeeper
{{- if eq .Values.policies.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-postgres
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: keycloak-postgres
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: keycloak
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: keycloak
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: keycloak-init
    - podSelector:
        matchLabels:
          app: haproxy
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: keycloak-postgres
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: keycloak-gatekeeper
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: keycloak-gatekeeper
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: haproxy
  egress:
  - {}
{{- end }}