{{- if eq .Values.components.landing.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: landing
  namespace: cloud-native-workstation
  labels:
    app: landing
spec:
  type: ClusterIP
  ports:
  - name: landing
    port: 443
    targetPort: {{ .Values.landing.targetPort }}
  selector:
    app: landing
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: landing
  namespace: cloud-native-workstation
  labels:
    app: landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: landing
  template:
    metadata:
      labels:
        app: landing
    spec:
      containers:
      - name: landing
        image: {{ .Values.landing.image }}
        resources: {{- toYaml .Values.components.landing.resources | nindent 10 }}
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: landing
  namespace: cloud-native-workstation
spec:
  podSelector:
    matchLabels:
      app: landing
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: keycloak-gatekeeper
{{- end }}