apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: requiredlabels
spec:
  crd:
    spec:
      names:
        kind: RequiredLabels
      validation:
        openAPIV3Schema:
          properties:
            labels:
              type: array
              items: string
  targets:
  - target: admission.k8s.gatekeeper.sh
    rego: |
      package requiredlabels
      violation[{"msg": msg, "details": {"missing_labels": missing}}] {
        provided := {label | input.review.object.metadata.labels[label]}
        required := {label | label := input.parameters.labels[_]}
        missing := required - provided
        count(missing) > 0
        msg := sprintf("you must provide labels: %v", [missing])
      }
---
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: deploymentselector
spec:
  crd:
    spec:
      names:
        kind: DeploymentSelector
      validation:
        openAPIV3Schema:
          properties:
            selector:
              type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package deploymentselector
        violation[{"msg": msg, "details": {"missing_selector": missing}}] {
          not input.review.object.spec.selector.matchLabels[input.parameters.selector]
          missing := input.parameters.selector
          msg := sprintf("you must include the deployment label selector: %v", [input.parameters.selector])
        }
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredLabels
metadata:
  name: app-label-on-pods
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces:
    - "cloud-native-workstation"
  parameters:
    labels: ["app"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DeploymentSelector
metadata:
  name: app-label-selector-for-deployments
spec:
  match:
    kinds:
    - apiGroups: ["apps"]
      kinds: ["Deployment"]
    namespaces:
    - "cloud-native-workstation"
  parameters:
    selector: "app"