{{- if eq .Values.policies.enabled true }}
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: RequiredLabels
metadata:
  name: app-label-on-pods
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces:
    - {{ .Values.namespace }}
  parameters:
    labels: ["app"]
---
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: DeploymentSelector
metadata:
  name: app-label-selector-for-deployments
spec:
  match:
    kinds:
    - apiGroups: ["apps"]
      kinds: ["Deployment"]
    namespaces:
    - {{ .Values.namespace }}
  parameters:
    selector: "app"
{{- end }}