{{- if eq .Values.components.selenium.enabled true }}
apiVersion: v1
kind: Service
metadata:
  name: selenium
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: selenium
    port: 80
    targetPort: 4444
  selector:
    app: {{ .Release.Name }}-selenium-hub
---
apiVersion: v1
kind: Service
metadata:
  name: chrome-vnc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: vnc
    port: 5900
  selector:
    app: {{ .Release.Name }}-selenium-chrome-debug
---
apiVersion: v1
kind: Service
metadata:
  name: novnc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  ports:
  - name: novnc
    port: 80
    targetPort: 6080
  selector:
    app: novnc
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novnc
  namespace: {{ .Values.namespace }}
  labels:
    app: novnc
spec:
  replicas: 1
  selector:
    matchLabels:
      app: novnc
  template:
    metadata:
      labels:
        app: novnc
    spec:
      {{ toYaml .Values.podDefaults | nindent 6 }}
      containers:
      - image: {{ .Values.docker.registry }}/cloud-native-workstation-novnc:{{ .Values.docker.tag }}
        imagePullPolicy: Always
        name: novnc
        command: ["/bin/bash", "-c"]
        args:
        - "bash /opt/novnc/utils/novnc_proxy --vnc chrome-vnc:5900"
        resources: {{- toYaml .Values.components.selenium.novnc.resources | nindent 10 }}
      restartPolicy: Always
{{- if eq .Values.policies.enabled true }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: novnc
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: novnc
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: ingress-nginx
  egress:
  - {}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: selenium
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-selenium-hub
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - {}
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-selenium-chrome-debug
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: chrome-vnc
  namespace: {{ .Values.namespace }}
spec:
  podSelector:
    matchLabels:
      app: {{ .Release.Name }}-selenium-chrome-debug
  policyTypes:
  - Egress
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: {{ .Release.Name }}-selenium-hub
    - podSelector:
        matchLabels:
          app: novnc
  egress:
  - {}
{{- end }}
{{- end }}