{{- if eq .Values.policies.enabled true }}
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: ResourceLimit
metadata:
  name: containers-must-have-limits
spec:
  match:
    kinds:
    - apiGroups: [""]
      kinds: ["Pod"]
    namespaces:
    - {{ .Release.Namespace }}
{{- end }}