apiVersion: v1
name: cloud-native-workstation
version: 0.11.0
dependencies:
- name: sonarqube
  version: 9.8.2
  repository: https://oteemo.github.io/charts/
  condition: sonarqube.enabled
- name: redis
  version: 15.5.5
  repository: https://charts.bitnami.com/bitnami/