# Domain for your workstation
domain: example.com

# Values based on provisioning mechanism
aws:
  efs: false

# Authentication (used across subsystems)
authentication:
  username: workstation
  # Change me!
  password: M@inz!DE

# Network policies and OPA constraint templates
policies:
  enabled: true

# Defaults applied to most pods
podDefaults:
  automountServiceAccountToken: false
  serviceAccountName: workstation-default

# Certbot for automated TLS certificate provisioning
certbot:
  enabled: true
  # Valid types are "google", "aws", and "cloudflare"
  type: google
  email: admin@example.com
  resources: {}

# For various seeding and initialization jobs
initializers:
  image: ndebuhr/cloud-native-workstation-initializers:v0.13.0
  resources: {}

# Keycloak
keycloak:
  # Change me!
  clientSecret: OkSR7DMXAXzIrZIoWyN8yh0sFkiYrfJd
  # Change me!
  cookieSecret: 2u2iS0FH7pPjOUUn
  resources: {}
  operator:
    image: quay.io/keycloak/keycloak-operator:16.1.0
    resources: {}
  postgres:
    resources: {}

# For protecting oauth2 proxied subsystems
oauth2Proxy:
  image: quay.io/oauth2-proxy/oauth2-proxy:v7.2.1
  resources: {}

# Code Server
code:
  enabled: true
  image: ndebuhr/cloud-native-workstation-code-server:v0.13.0
  # For accessing cloud resources over VPN, set ovpn=true and:
  # kubectl create secret generic client-ovpn --from-file=client.ovpn
  ovpn: false
  storage: 32Gi
  resources: {}
  dind:
    image: docker:20-dind
    storage: 16Gi
    resources: {}

# PgWeb
pgweb:
  enabled: false
  image: ndebuhr/cloud-native-workstation-pgweb:v0.13.0
  # For accessing databases over VPN, set ovpn=true and:
  # kubectl create secret generic client-ovpn --from-file=client.ovpn
  ovpn: false
  resources: {}

# SFTP server
sftp:
  enabled: false
  image: atmoz/sftp:debian
  storage: 32Gi
  resources: {}

# Selenium Grid
selenium:
  enabled: false
  hub:
    image: selenium/hub:4.1
    resources: {}
  chrome:
    enabled: false
    image: selenium/node-chrome:4.1
    resources: {}
  firefox:
    enabled: false
    image: selenium/node-firefox:4.1
    resources: {}
  edge:
    enabled: false
    image: selenium/node-edge:4.1
    resources: {}

# Jupyter notebook
jupyter:
  enabled: false
  image: ndebuhr/cloud-native-workstation-jupyter:v0.13.0
  # For accessing cloud resources over VPN, set ovpn=true and:
  # kubectl create secret generic client-ovpn --from-file=client.ovpn
  ovpn: false
  storage: 32Gi
  gpu:
    enabled: false
    # If you are using the provided terraform provisioning, this value
    # should match the gcp_gpu variable value
    name: nvidia-tesla-t4
  resources: {}
    # requests:
    #   cpu: 0
    #   memory: 0
    #   nvidia.com/gpu: 1
    # limits:
    #   cpu: 4
    #   memory: 8Gi
    #   nvidia.com/gpu: 1

# Landing page
landing:
  enabled: false
  image: gcr.io/google-samples/hello-app:2.0
  targetPort: 8080
  resources: {}

# SonarQube
sonarqube:
  enabled: false
  initContainers:
    resources: {}
  postgresql:
    resources: {}
  resources: {}

# Apache Guacamole
guacamole:
  enabled: false
  image: guacamole/guacamole:1.3.0
  resources: {}
  guacd:
    image: guacamole/guacd:1.3.0
    resources: {}
  postgres:
    image: postgres:9.6
    storage: 16Gi
    resources: {}

# Kanboard
kanboard:
  enabled: false
  image: kanboard/kanboard:v1.2.21
  storage: 128Gi
  resources: {}

# Prometheus
prometheus:
  enabled: false
  image: prom/prometheus:v2.32.1
  storage: 16Gi
  resources: {}
  kubeStateMetrics:
    enabled: false
    image: quay.io/coreos/kube-state-metrics:v1.9.8
    resources: {}

# Grafana
grafana:
  enabled: false
  image: grafana/grafana:8.3.3
  dashboards:
    prometheus:
      plugin:
      - dashboards/prometheus_stats.json
      - dashboards/prometheus_2_stats.json
      - dashboards/grafana_stats.json
      community:
      - 13332
  storage: 8Gi
  resources: {}

# Redis for OAuth2 Proxy session storage
redis:
  architecture: standalone
  auth:
    enabled: false
  master:
    podLabels:
      app: redis-master
    resources: {}