# Domain for your workstation
domain: example.com
# Public images on Docker Hub
docker:
  registry: ndebuhr
  tag: v0.9.0
aws:
  efs: false
# Certbot details
certbot:
  # Valid types are "google", "aws", and "cloudflare"
  type: google
  email: admin@example.com
# Keycloak security
keycloak:
  # Change me!
  clientSecret: OkSR7DMXAXzIrZIoWyN8yh0sFkiYrfJd
  # Change me!
  cookieSecret: 2u2iS0FH7pPjOUUn
# Authentication for Code Server and Keycloak
authentication:
  username: workstation
  # Change me!
  password: M@inz!DE
# Network policies and OPA constraint templates
policies:
  enabled: true
# Components included in the workstation
components:
  keycloak:
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "4Gi"
        cpu: "2"
    operator:
      resources:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: "1Gi"
          cpu: "500m"
    postgres:
      resources:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: "4Gi"
          cpu: "2"
  initializers:
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "256Mi"
        cpu: "125m"
  oauth2Proxy:
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "2Gi"
        cpu: "1"
  code:
    enabled: true
    # For accessing cloud resources over VPN, set ovpn=true and:
    # kubectl create secret generic client-ovpn --from-file=client.ovpn
    ovpn: false
    storage: 32Gi
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "8Gi"
        cpu: "4"
    dind:
      image: docker
      tag: 19-dind
      storage: 16Gi
      resources:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: "4Gi"
          cpu: "2"
  pgweb:
    enabled: false
    # For accessing databases over VPN, set ovpn=true and:
    # kubectl create secret generic client-ovpn --from-file=client.ovpn
    ovpn: false
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: 8Gi
        cpu: 2
  selenium:
    enabled: false
    novnc:
      resources:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: "4Gi"
          cpu: "2"
  jupyter:
    enabled: false
    # For accessing cloud resources over VPN, set ovpn=true and:
    # kubectl create secret generic client-ovpn --from-file=client.ovpn
    ovpn: false
    storage: 32Gi
    gpu:
      enabled: false
      # If you are using the provided terraform provisioning, this value
      # should match the gcp_gpu variable value
      name: nvidia-tesla-t4
    resources:
      requests:
        memory: 0
        cpu: 0
        # nvidia.com/gpu: 1
      limits:
        memory: "8Gi"
        cpu: "4"
        # nvidia.com/gpu: 1
  certbot:
    enabled: true
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "256Mi"
        cpu: "125m"
  landing:
    enabled: false
    image: gcr.io/google-samples/hello-app:2.0
    targetPort: 8080
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "2Gi"
        cpu: "1"
  sonarqube:
    enabled: false
  guacamole:
    enabled: false
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "4Gi"
        cpu: "1"
    guacd:
      resources:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: "4Gi"
          cpu: "1"
    postgres:
      storage: 16Gi
      resources:
        requests:
          memory: 0
          cpu: 0
        limits:
          memory: "4Gi"
          cpu: "2"
  prometheus:
    enabled: false
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "2Gi"
        cpu: "1"
  grafana:
    enabled: false
    dashboards:
      prometheus:
        plugin:
        - dashboards/prometheus_stats.json
        - dashboards/prometheus_2_stats.json
        - dashboards/grafana_stats.json
        community:
        - 13332
    storage: 8Gi
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "2Gi"
        cpu: "1"
# Ingress targets
access:
- name: code
- name: hugo
- name: pgweb
- name: selenium
- name: novnc
- name: jupyter
- name: landing
- name: sonarqube
- name: guacamole
- name: prometheus
- name: grafana
# Defaults applied to most pods
podDefaults:
  automountServiceAccountToken: false
  serviceAccountName: workstation-default
# Additional component-specific configuration
selenium:
  hub:
    serviceType: ClusterIP
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        cpu: 1
        memory: 2Gi
  chromeDebug:
    enabled: true
    resources:
      requests:
        cpu: 0
        memory: 0
      limits:
        cpu: 2
        memory: 8Gi
    extraEnvs:
    - name: VNC_NO_PASSWORD
      value: "1"
sonarqube:
  initContainers:
    resources:
      requests:
        memory: 0
        cpu: 0
      limits:
        memory: "256Mi"
        cpu: "125m"
  postgresql:
    resources:
      requests:
        memory: "0"
        cpu: "0"
  resources:
    requests:
      memory: 0
      cpu: 0
    limits:
      cpu: 1
      memory: 2Gi