apiVersion: v2
name: cloud-native-workstation-prerequisites
version: 0.13.0
icon: https://raw.githubusercontent.com/ndebuhr/cloud-native-workstation/master/images/cnw.png
dependencies:
- name: ingress-nginx
  version: 4.0.13
  repository: https://kubernetes.github.io/ingress-nginx
- name: gatekeeper
  version: 3.7.0
  repository: https://open-policy-agent.github.io/gatekeeper/charts
- name: aws-efs-csi-driver
  version: 2.2.2
  repository: https://kubernetes-sigs.github.io/aws-efs-csi-driver/
  condition: aws-efs-csi-driver.enabled