apiVersion: v1
name: cloud-native-workstation-prerequisites
version: 0.7.1
dependencies:
- name: ingress-nginx
  version: 4.0.3
  repository: https://kubernetes.github.io/ingress-nginx
- name: gatekeeper
  version: 3.6.0
  repository: https://open-policy-agent.github.io/gatekeeper/charts