# Domain for your workstation
domain: example.com
# Public images on Docker Hub
docker:
  registry: ndebuhr
  tag: latest
# Certbot details
certbot:
  # Valid types are "google" and "cloudflare"
  type: google
  email: admin@example.com
# Keycloak security
keycloak:
  # Change me!
  clientSecret: OkSR7DMXAXzIrZIoWyN8yh0sFkiYrfJd
  # Change me!
  encryptionKey: 2u2iS0FH7pPjOUUn
# Authentication for Code Server and Keycloak
authentication:
  username: workstation
  # Change me!
  password: M@inz!DE
# Components included in the workstation
components:
  keycloak:
    resources:
      requests: {}
        # memory: "512Mi"
        # cpu: "250m"
      limits: {}
        # memory: "2Gi"
        # cpu: "1"
    postgres:
      resources:
        requests: {}
          # memory: "512Mi"
          # cpu: "250m"
        limits: {}
          # memory: "2Gi"
          # cpu: "1"
    gatekeepers:
      resources:
        requests: {}
          # memory: "128Mi"
          # cpu: "50m"
        limits: {}
          # memory: "1Gi"
          # cpu: "500m"
  haproxy:
    resources:
      requests: {}
        # memory: "256Mi"
        # cpu: "100m"
      limits: {}
        # memory: "1Gi"
        # cpu: "500m"
  code:
    enabled: true
    resources:
      requests: {}
        # memory: "2Gi"
        # cpu: "1"
      limits: {}
        # memory: "6Gi"
        # cpu: "3"
    dind:
      image: docker
      tag: 19-dind
      resources:
        requests: {}
          # memory: "1Gi"
          # cpu: "500m"
        limits: {}
          # memory: "3Gi"
          # cpu: "1.5"
  selenium:
    enabled: false
    novnc:
      resources:
        requests: {}
          # memory: "2Gi"
          # cpu: "1"
        limits: {}
          # memory: "6Gi"
          # cpu: "3"
  jupyter:
    enabled: false
    resources:
      requests: {}
        # memory: "2Gi"
        # cpu: "500m"
      limits: {}
        # memory: "6Gi"
        # cpu: "1.5"
  certbot:
    enabled: true
  landing:
    enabled: false
    resources:
      requests: {}
        # memory: "256Mi"
        # cpu: "125m"
      limits: {}
        # memory: "1Gi"
        # cpu: "500m"
  sonarqube:
    enabled: false
  guacamole:
    enabled: false
    resources:
      requests: {}
        # memory: "2Gi"
        # cpu: "1"
      limits: {}
        # memory: "6Gi"
        # cpu: "3"
    guacd:
      resources:
        requests: {}
          # memory: "2Gi"
          # cpu: "1"
        limits: {}
          # memory: "6Gi"
          # cpu: "3"
    postgres:
      resources:
        requests: {}
          # memory: "1Gi"
          # cpu: "500m"
        limits: {}
          # memory: "3Gi"
          # cpu: "1.5"
# Ports for the component endpoints
access:
- name: keycloak
  port: 8080
- name: code
  port: 3000
- name: hugo
  port: 1313
- name: selenium
  port: 4444
- name: chrome
  port: 6080
- name: jupyter
  port: 8888
- name: landing
  port: 443
- name: sonarqube
  port: 9000
- name: guacamole
  port: 8081
# Additional component-specific configuration
selenium:
  hub:
    serviceType: ClusterIP
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  chromeDebug:
    enabled: true
    resources:
      limits:
        cpu: 1
        memory: 4Gi
    extraEnvs:
    - name: VNC_NO_PASSWORD
      value: "1"
landing:
  image: gcr.io/google-samples/hello-app:2.0
  targetPort: 8080