# Domain for your workstation
domain: example.com
# Public images on Docker Hub
docker:
  registry: ndebuhr
  tag: latest
# Certbot details
certbot:
  # Valid types are "google" and "cloudflare"
  type: google
  email: admin@example.com
# Keycloak security
keycloak:
  # Change me!
  clientSecret: OkSR7DMXAXzIrZIoWyN8yh0sFkiYrfJd
  # Change me!
  encryptionKey: 2u2iS0FH7pPjOUUn
# Authentication for Code Server and Keycloak
authentication:
  username: workstation
  # Change me!
  password: M@inz!DE
# Components included in the workstation
components:
  code:
    enabled: true
  hackmd:
    enabled: false
  kdenlive:
    enabled: false
  selenium:
    enabled: false
  jupyter:
    enabled: false
  certbot:
    enabled: true
  landing:
    enabled: false
  sonarqube:
    enabled: false
  guacamole:
    enabled: false
# Ports for the component endpoints
access:
- name: keycloak
  port: 8080
- name: code
  port: 3000
- name: hugo
  port: 1313
- name: hackmd
  port: 3003
- name: kdenlive-desktop
  port: 6901
- name: kdenlive-audio
  port: 8090
- name: selenium
  port: 4444
- name: chrome
  port: 6080
- name: jupyter
  port: 8888
- name: landing
  port: 443
- name: sonarqube
  port: 9000
- name: guacamole
  port: 8081
# Additional component-specific configuration
hackmd:
  persistence:
    size: 64Gi
  postgresql:
    postgresPassword: M@inz!
selenium:
  hub:
    serviceType: ClusterIP
    resources:
      limits:
        cpu: 1
        memory: 1Gi
  chromeDebug:
    enabled: true
    resources:
      limits:
        cpu: 1
        memory: 4Gi
    extraEnvs:
    - name: VNC_NO_PASSWORD
      value: "1"
landing:
  image: gcr.io/google-samples/hello-app:2.0
  targetPort: 8080