name: build

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: setup up qemu
      uses: docker/setup-qemu-action@v1

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: build code server image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/DockerfileCodeServer
        push: false
        tags: ndebuhr/cloud-native-workstation-code-server:latest

    - name: build keycloak seeding image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/DockerfileInitializers
        push: false
        tags: ndebuhr/cloud-native-workstation-initializers:latest

    - name: build novnc image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/DockerfileNovnc
        push: false
        tags: ndebuhr/cloud-native-workstation-novnc:latest
