name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Install gcloud cli
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install terraform cli
      uses: hashicorp/setup-terraform@v1

    - name: Install helm cli
      run: |
        wget https://get.helm.sh/helm-v3.5.4-linux-amd64.tar.gz
        tar xfvz helm-v3.5.4-linux-amd64.tar.gz linux-amd64/helm
        install linux-amd64/helm /usr/local/bin/

    - name: Provision a GKE cluster
      working-directory: ./core
      run: |
        terraform init
        terraform apply -auto-approve || terraform destroy -auto-approve && exit 1

    - name: Deploy to GKE
      working-directory: ./helm
      run: |
        helm install cloud-native-workstation . || exit 1
        helm uninstall cloud-native-workstation

    - name: Deprovision a GKE cluster
      working-directory: ./core
      run: |
        terraform destroy -auto-approve
