name: deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v2
      with:
        submodules: 'true'

    - name: Install gcloud cli
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install helm
      run: |
        gcloud container clusters get-credentials core-qa --zone us-central1-a
        alias helm="docker run -ti --rm -v $(pwd):/apps -v ~/.kube:/root/.kube -v ~/.helm:/root/.helm alpine/helm:3.5.4"

    - name: Generate a password
      run: |
        echo "PASSWORD=$(head /dev/urandom | tr -dc A-Za-z0-9 | head -c10)" >> $GITHUB_ENV

    - name: Setup namespace
      run: |
        kubectl create namespace workstation-$GITHUB_RUN_NUMBER

    - name: Create DNS credentials
      run: |
        cp $GOOGLE_APPLICATION_CREDENTIALS google.json
        kubectl create secret generic google-json \
            --from-file google.json \
            --namespace workstation-$GITHUB_RUN_NUMBER

    - name: Update Helm dependencies
      working-directory: ./deploy/
      run: |
        helm dep update

    - name: Deploy a workstation
      working-directory: ./deploy/
      run: |
        helm install workstation . \
            --namespace workstation-$GITHUB_RUN_NUMBER \
            --set domain=$GITHUB_RUN_NUMBER.${{ secrets.ROOT_URL }} \
            --set policies.enabled=false \
            --set authentication.password=$PASSWORD \
            --set certbot.enabled=true \
            --set certbot.email=admin@$GITHUB_RUN_NUMBER.${{ secrets.ROOT_URL }} \
            --set oauth2Proxy.enabled=true \
            --set pgweb.enabled=false \
            --set sftp.enabled=false \
            --set selenium.enabled=true \
            --set selenium.chrome.enabled=true \
            --set selenium.firefox.enabled=true \
            --set selenium.edge.enabled=true \
            --set jupyter.enabled=false \
            --set landing.enabled=true \
            --set sonarqube.enabled=false \
            --set guacamole.enabled=false \
            --set kanboard.enabled=false \
            --set prometheus.enabled=false \
            --set grafana.enabled=false \
            --timeout 5m0s \
            --wait || echo $?

    - name: Create DNS records
      run: |
        IP=$(kubectl get ingress main -o json --namespace workstation-$GITHUB_RUN_NUMBER | jq .status.loadBalancer.ingress[0].ip | sed 's/"//g') || exit $?
        gcloud dns --project=${{ secrets.GCP_PROJECT_ID }} record-sets transaction start --zone=${{ secrets.DNS_ZONE }}
        gcloud dns --project=${{ secrets.GCP_PROJECT_ID }} record-sets transaction add $IP --name="*.$GITHUB_RUN_NUMBER.${{ secrets.ROOT_URL }}" --ttl=300 --type=A --zone=${{ secrets.DNS_ZONE }}
        gcloud dns --project=${{ secrets.GCP_PROJECT_ID }} record-sets transaction execute --zone=${{ secrets.DNS_ZONE }}

    - name: Create access instructions and helm release status
      run: |
        echo "You can access your instance at code.$GITHUB_RUN_NUMBER.${{ secrets.ROOT_URL }}, using the username \"workstation\" and password \"$PASSWORD\"" > access.txt
        helm status workstation --namespace workstation-$GITHUB_RUN_NUMBER > status.txt

    - uses: actions/upload-artifact@v3
      with:
        name: access
        path: access.txt

    - uses: actions/upload-artifact@v3
      with:
        name: status
        path: status.txt