name: deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: Install gcloud cli
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Install helm
      run: |
        gcloud container clusters get-credentials cloud-native-workstation --zone -us-central1-a
        alias helm="docker run -ti --rm -v $(pwd):/apps -v ~/.kube:/root/.kube -v ~/.helm:/root/.helm alpine/helm:3.5.4"

    - name: Install terraform cli
      uses: hashicorp/setup-terraform@v1

    - name: Provision a GKE cluster
      working-directory: ./terraform
      run: |
        terraform init
        terraform apply -auto-approve -var="gcp_project=${{ secrets.GCP_PROJECT_ID }}"

    - name: Deploy to GKE
      working-directory: ./helm
      run: |
        helm install cloud-native-workstation .

    - name: Undeploy
      working-directory: ./helm
      run: |
        helm uninstall cloud-native-workstation

    - name: Deprovision
      working-directory: ./core
      run: |
        terraform destroy -auto-approve
