name: publish

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: code checkout
      uses: actions/checkout@v2
      with:
        # Disabling shallow clone is recommended for improving relevancy of reporting
        fetch-depth: 0

    - name: setup up qemu
      uses: docker/setup-qemu-action@v1

    - name: setup docker buildx
      uses: docker/setup-buildx-action@v1

    - name: login to docker hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: meta for code server image
      id: meta-code-server
      uses: docker/metadata-action@v3
      with:
        images: ndebuhr/cloud-native-workstation-code-server

    - name: build and push code server image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/DockerfileCodeServer
        push: true
        tags: ${{ steps.meta-code-server.outputs.tags }}

    - name: meta for keycloak seeding image
      id: meta-keycloak-seeding
      uses: docker/metadata-action@v3
      with:
        images: ndebuhr/cloud-native-workstation-keycloak-seeding

    - name: build and push keycloak seeding image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/DockerfileKeycloakSeeding
        push: true
        tags: ${{ steps.meta-keycloak-seeding.outputs.tags }}

    - name: meta for novnc image
      id: meta-novnc
      uses: docker/metadata-action@v3
      with:
        images: ndebuhr/cloud-native-workstation-novnc

    - name: build and push novnc image
      uses: docker/build-push-action@v2
      with:
        context: ./docker
        file: ./docker/DockerfileNovnc
        push: true
        tags: ${{ steps.meta-novnc.outputs.tags }}
